name: diss_parameter_estimation
channels:
  - conda-forge
dependencies:
  - python==3.14.3
  - cadet==5.1.1  # build h56c1e75_1
  - pytest
  - pip
  - pip:
      - cadet-python==1.2.0
      - cadet-process==0.12.0
      - cadet-rdm==1.1.2
      - numpy==2.4.4
      - scipy==1.17.1
      - pymoo==0.6.1.6
